title: Home
#
custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
#
resources: !include_dir_list lovelace/resources
#
views:
  - !include lovelace/views/main_view.yaml
  - !include lovelace/views/main_control.yaml
  - !include lovelace/views/media_control.yaml
  - !include lovelace/views/statistics.yaml
  - !include lovelace/views/testing.yaml